### ISSUE TITLE
Error in checkForRemoteErrors(val)

### ISSUE THREAD

**Issue by tothuhien** [thibautjombart/outbreaker#5]
Hi,
I'm trying to run outbreaker.parallel on just 14 sequences, 4 runs and 1e6 iterations, but I've always got the error:
Error in checkForRemoteErrors(val) : 
  4 nodes produced errors; first error: line 2001 did not have 51 elements
Do you know what goes wrong here? Thank you very much 
Hien

**Comment by thibautjombart** [comment]
Hi Hien, 
the error suggests that it is not a parallel-version problem. Can you try the serial version and see what error messages are? Also, which version of R and outbreaker are you using?

**Comment by tothuhien** [comment]
Hi Thibaut. The serial version works, and after finishing the serial version I tried the parallel version again and it worked this time without errors. I don't know why, but I think it was because the last time when I run the parallel-version, I've stopped it when it hadn't finished yet. That may cause the problem. Thanks a lot.

**Comment by thibautjombart** [comment]
OK great, thanks for the update!
Best
Thibaut


--
Dr Thibaut Jombart
Lecturer, Department of Infectious Disease Epidemiology, Imperial College
London
Head of RECON: repidemicsconsortium.org
sites.google.com/site/thibautjombart/
github.com/thibautjombart
Twitter: @TeebzR <http://twitter.com/TeebzR>
+44(0)20 7594 3658
